name: Docusaurus-website-build

on:
  push:
    branch: master
    paths:
      - '.github/workflows/docusaurus.yml'
      - 'docs/**'
      - 'website/**'
  pull_request:
    paths:
      - '.github/workflows/docusaurus.yml'
      - 'docs/**'
      - 'website/**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  githubUserEmail: infra@finos.org
  githubUserName: finos-admin
  repoName: ${{ github.event.repository.name }}
  patchScriptUrl: https://raw.githubusercontent.com/finos/open-developer-platform/master/scripts/patch-docusaurus-config.sh
  resetScriptUrl: https://raw.githubusercontent.com/finos/open-developer-platform/master/scripts/reset-gh-pages.sh

jobs:
  website-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - run: mkdir -p public
    - name: Install Node
      uses: actions/setup-node@v1
    - name: Install Website deps
      run: npm install --prefix website
    - name: Patch forked version
      run: |
        REPO="${{ github.repository }}"
        REPO_ORG=${REPO%"/"*}
        if [ "$REPO_ORG" != "finos" ]
        then echo "Repo organization is '$REPO_ORG', patching docusaurus configuration to work on a forked repo" ; curl ${{ env.patchScriptUrl }} |  bash -s -- ${{ env.repoName }} $REPO_ORG
        else echo "Skipping patching, as this is the FINOS Organization"
        fi
    - name: Build Website
      run: |
        npm run build --prefix website
        git checkout website/siteConfig.js
    - name: Commit files
      run: |
        git checkout -b gh-pages || git checkout gh-pages
        curl ${{ env.resetScriptUrl }} |  bash -s
        if [ -d "website/build/${{ env.repoName }}" ]
        then cp -Rf website/build/${{ env.repoName }}/* .
        else cp -Rf website/build/* .
        fi
        rm -rf website public
        git add .
        git config --local user.email "${{ env.githubUserEmail }}"
        git config --local user.name "${{ env.githubUserName }}"
        git commit -m "Docusaurus Action - pushing website changes" -a || true
    - name: Push changes
      if: github.event_name == 'push'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
    - name: Add comment to PR
      if: github.event_name == 'pull_request'
      uses: unsplash/comment-on-pr@master
      with:
        msg: "Website preview available at https://${{ github.actor }}.github.io/${{ env.repoName }}"